// Centralized query key factory so socket handlers and query hooks agree on shape.
export const queryKeys = {
  servers: () => ["servers"] as const,
  server: (serverId: string) => ["servers", serverId] as const,
  channels: (serverId: string) => ["channels", serverId] as const,
  channelOverwrites: (channelId: string) => ["channelOverwrites", channelId] as const,
  members: (serverId: string) => ["members", serverId] as const,
  roles: (serverId: string) => ["roles", serverId] as const,
  invites: (serverId: string) => ["invites", serverId] as const,
  auditLog: (serverId: string) => ["auditLog", serverId] as const,
  bans: (serverId: string) => ["bans", serverId] as const,
  messages: (channelId: string) => ["messages", "channel", channelId] as const,
  dmMessages: (conversationId: string) => ["messages", "dm", conversationId] as const,
  dms: () => ["dms"] as const,
  unread: (serverId: string) => ["unread", serverId] as const,
  search: (serverId: string, q: string) => ["search", serverId, q] as const,
  me: () => ["me"] as const,
  invitePreview: (code: string) => ["invitePreview", code] as const,
  myMentions: () => ["myMentions"] as const,
  serverWebhooks: (serverId: string) => ["webhooks", "server", serverId] as const,
  myApplications: () => ["myApplications"] as const,
  friends: () => ["friends"] as const,
  friendRequests: () => ["friendRequests"] as const,
  blockedUsers: () => ["blockedUsers"] as const,
  friendSuggestions: () => ["friendSuggestions"] as const,
  voiceState: (serverId: string) => ["voiceState", serverId] as const,
  // The tag is part of the key so a filtered feed doesn't overwrite the unfiltered one in the
  // cache — going back to "For You" after browsing a tag would otherwise show the tag's results.
  feed: (tag?: string | null) => (tag ? (["feed", "tag", tag] as const) : (["feed"] as const)),
  feedFollowing: () => ["feed", "following"] as const,
  myVideos: () => ["myVideos"] as const,
  staffVideos: (status: string) => ["staffVideos", status] as const,
  staffVideoCounts: () => ["staffVideoCounts"] as const,
  staffAudit: () => ["staffAudit"] as const,
};
