import { describe, expect, it } from "vitest";
import { generateSync } from "otplib";
import {
  decryptSecret,
  encryptSecret,
  generateBackupCodes,
  generateSecret,
  normaliseBackupCode,
  otpauthURI,
  verifyCode,
} from "./totp.js";

/**
 * The second factor is only worth having if it actually rejects things, so most of these assert a
 * refusal rather than an acceptance. A TOTP implementation that returns true unconditionally passes
 * every "valid code works" test ever written.
 */
describe("TOTP", () => {
  it("verifies a code produced by a real authenticator implementation", () => {
    const secret = generateSecret();
    // Generated by otplib's own algorithm — the same computation any authenticator app performs,
    // rather than a value this module made up and then agreed with itself about.
    const code = generateSync({ secret, strategy: "totp" });
    expect(verifyCode({ token: code, secret })).toBe(true);
  });

  it("rejects a code produced from a DIFFERENT secret", () => {
    // The assertion that matters. If verification ignored the secret, every test above would still
    // pass and every account would accept every code.
    const secret = generateSecret();
    const code = generateSync({ secret: generateSecret(), strategy: "totp" });
    expect(verifyCode({ token: code, secret })).toBe(false);
  });

  it("rejects malformed input without throwing", () => {
    const secret = generateSecret();
    for (const token of ["", "abc", "12345", "1234567", "!!!!!!", "000000 000000"]) {
      expect(() => verifyCode({ token, secret })).not.toThrow();
      expect(verifyCode({ token, secret })).toBe(false);
    }
  });

  it("tolerates spaces, since authenticator apps display codes as '123 456'", () => {
    const secret = generateSecret();
    const code = generateSync({ secret, strategy: "totp" });
    const spaced = `${code.slice(0, 3)} ${code.slice(3)}`;
    expect(verifyCode({ token: spaced, secret })).toBe(true);
  });

  it("builds an otpauth URI an authenticator app can scan", () => {
    const secret = generateSecret();
    const uri = otpauthURI({ secret, accountName: "alice" });
    expect(uri.startsWith("otpauth://totp/")).toBe(true);
    expect(uri).toContain("Lumina");
    expect(uri).toContain(secret);
  });
});

describe("secret encryption", () => {
  it("round-trips", () => {
    const secret = generateSecret();
    expect(decryptSecret(encryptSecret(secret))).toBe(secret);
  });

  it("produces different ciphertext each time for the same input", () => {
    // A fresh IV per encryption. Without it, identical secrets produce identical rows, and the
    // database quietly reveals which accounts share one.
    const secret = generateSecret();
    expect(encryptSecret(secret)).not.toBe(encryptSecret(secret));
  });

  it("refuses a tampered ciphertext rather than returning garbage", () => {
    // GCM's auth tag is the point: flip a byte and decryption must fail, not silently yield a
    // different secret that would then reject every real code with no explanation.
    const encrypted = encryptSecret(generateSecret());
    const parts = encrypted.split(".");
    const body = Buffer.from(parts[3], "base64url");
    body[0] ^= 0xff;
    parts[3] = body.toString("base64url");
    expect(decryptSecret(parts.join("."))).toBeNull();
  });

  it("returns null rather than throwing on a value it cannot parse", () => {
    // Reached when JWT_ACCESS_SECRET has been rotated. It must degrade to "no working second
    // factor" so the user can fall back to a backup code — not throw a 500 into the login route.
    for (const bad of ["", "nonsense", "v1.only.three", "v2.a.b.c"]) {
      expect(decryptSecret(bad)).toBeNull();
    }
  });
});

describe("backup codes", () => {
  it("generates ten distinct codes", () => {
    const codes = generateBackupCodes();
    expect(codes).toHaveLength(10);
    expect(new Set(codes).size).toBe(10);
  });

  it("formats them in two groups of five digits", () => {
    // They get written on paper; an unbroken ten-character run is materially easier to mistype.
    for (const code of generateBackupCodes()) {
      expect(code).toMatch(/^\d{5}-\d{5}$/);
    }
  });

  it("normalises to bare digits so a code typed without the hyphen still matches", () => {
    const [code] = generateBackupCodes();
    expect(normaliseBackupCode(code)).toHaveLength(10);
    expect(normaliseBackupCode(code)).toBe(normaliseBackupCode(code.replace("-", "")));
    expect(normaliseBackupCode(` ${code} `)).toBe(normaliseBackupCode(code));
  });

  it("does not repeat across separate generations", () => {
    // A weak generator would show up here first. Two independent batches sharing a code would mean
    // recovery codes are predictable, which defeats the entire point of the second factor.
    const a = new Set(generateBackupCodes(50));
    const b = generateBackupCodes(50);
    expect(b.filter((code) => a.has(code))).toHaveLength(0);
  });
});
