// A small, curated unicode-emoji set with search keywords, for the composer's emoji button and the
// reaction picker. Deliberately hand-rolled rather than pulling a full emoji dataset dependency —
// no npm deps are added here, and a searchable shortlist covers the overwhelming majority of picks.
// Server custom emoji (fetched per-server) are layered on top of this at render time.
export interface EmojiEntry {
  char: string;
  /** Space-separated search terms. The first word doubles as the display name. */
  keywords: string;
}

export const EMOJI_SET: EmojiEntry[] = [
  { char: "😀", keywords: "grin smile happy" },
  { char: "😃", keywords: "smiley happy joy" },
  { char: "😄", keywords: "laugh happy joy" },
  { char: "😁", keywords: "beaming grin" },
  { char: "😆", keywords: "laughing lol xd" },
  { char: "😅", keywords: "sweat nervous laugh" },
  { char: "😂", keywords: "joy lol laughing tears" },
  { char: "🤣", keywords: "rofl rolling laughing" },
  { char: "🙂", keywords: "smile slight" },
  { char: "🙃", keywords: "upside down silly" },
  { char: "😉", keywords: "wink" },
  { char: "😊", keywords: "blush smile happy" },
  { char: "😇", keywords: "innocent angel halo" },
  { char: "😍", keywords: "heart eyes love" },
  { char: "🥰", keywords: "love hearts adore" },
  { char: "😘", keywords: "kiss blow" },
  { char: "😋", keywords: "yum tongue tasty" },
  { char: "😛", keywords: "tongue playful" },
  { char: "🤪", keywords: "zany crazy wild" },
  { char: "🤨", keywords: "raised eyebrow skeptical" },
  { char: "🧐", keywords: "monocle inspect thinking" },
  { char: "🤓", keywords: "nerd glasses" },
  { char: "😎", keywords: "cool sunglasses" },
  { char: "🥳", keywords: "party celebrate hat" },
  { char: "🤩", keywords: "star struck excited" },
  { char: "😏", keywords: "smirk sly" },
  { char: "😒", keywords: "unamused meh" },
  { char: "😞", keywords: "disappointed sad" },
  { char: "😔", keywords: "pensive sad" },
  { char: "😟", keywords: "worried" },
  { char: "😕", keywords: "confused" },
  { char: "🙁", keywords: "frown sad" },
  { char: "😣", keywords: "persevere struggle" },
  { char: "😖", keywords: "confounded" },
  { char: "😫", keywords: "tired weary" },
  { char: "😩", keywords: "weary tired" },
  { char: "🥺", keywords: "pleading puppy eyes begging" },
  { char: "😢", keywords: "cry sad tear" },
  { char: "😭", keywords: "sob crying loud" },
  { char: "😤", keywords: "triumph huff steam" },
  { char: "😠", keywords: "angry mad" },
  { char: "😡", keywords: "rage furious mad" },
  { char: "🤬", keywords: "swearing cursing angry" },
  { char: "🤯", keywords: "mind blown exploding" },
  { char: "😳", keywords: "flushed embarrassed" },
  { char: "🥵", keywords: "hot heat sweating" },
  { char: "🥶", keywords: "cold freezing" },
  { char: "😱", keywords: "scream fear shocked" },
  { char: "😨", keywords: "fearful scared" },
  { char: "😰", keywords: "anxious sweat" },
  { char: "😥", keywords: "sad relieved" },
  { char: "🤔", keywords: "thinking hmm" },
  { char: "🤗", keywords: "hug hugging" },
  { char: "🤭", keywords: "giggle oops hand mouth" },
  { char: "🤫", keywords: "shush quiet secret" },
  { char: "😐", keywords: "neutral meh" },
  { char: "😶", keywords: "no mouth speechless" },
  { char: "😴", keywords: "sleep sleeping zzz" },
  { char: "🤤", keywords: "drool" },
  { char: "😷", keywords: "mask sick" },
  { char: "🤒", keywords: "sick thermometer ill" },
  { char: "🤮", keywords: "vomit sick puke" },
  { char: "🥴", keywords: "woozy dizzy" },
  { char: "😵", keywords: "dizzy dead" },
  { char: "🤠", keywords: "cowboy" },
  { char: "😈", keywords: "devil evil grin" },
  { char: "👻", keywords: "ghost boo spooky" },
  { char: "💀", keywords: "skull dead" },
  { char: "👽", keywords: "alien ufo" },
  { char: "🤖", keywords: "robot bot" },
  { char: "💩", keywords: "poop pile" },
  { char: "👍", keywords: "thumbsup yes like approve" },
  { char: "👎", keywords: "thumbsdown no dislike" },
  { char: "👌", keywords: "ok okay perfect" },
  { char: "🤌", keywords: "pinched fingers italian" },
  { char: "✌️", keywords: "peace victory" },
  { char: "🤞", keywords: "fingers crossed luck" },
  { char: "🤟", keywords: "love you rock" },
  { char: "🤙", keywords: "call me shaka" },
  { char: "👏", keywords: "clap applause bravo" },
  { char: "🙌", keywords: "raised hands praise celebrate" },
  { char: "🙏", keywords: "pray thanks please" },
  { char: "💪", keywords: "muscle strong flex" },
  { char: "👋", keywords: "wave hello hi bye" },
  { char: "🫶", keywords: "heart hands love" },
  { char: "✍️", keywords: "writing hand" },
  { char: "🔥", keywords: "fire lit hot flame" },
  { char: "⭐", keywords: "star" },
  { char: "🌟", keywords: "star glowing sparkle" },
  { char: "✨", keywords: "sparkles shiny" },
  { char: "⚡", keywords: "zap lightning bolt" },
  { char: "💥", keywords: "boom explosion collision" },
  { char: "🎉", keywords: "party tada celebrate confetti" },
  { char: "🎊", keywords: "confetti ball party" },
  { char: "🎈", keywords: "balloon party" },
  { char: "🎁", keywords: "gift present" },
  { char: "❤️", keywords: "heart love red" },
  { char: "🧡", keywords: "orange heart love" },
  { char: "💛", keywords: "yellow heart love" },
  { char: "💚", keywords: "green heart love" },
  { char: "💙", keywords: "blue heart love" },
  { char: "💜", keywords: "purple heart love" },
  { char: "🖤", keywords: "black heart love" },
  { char: "🤍", keywords: "white heart love" },
  { char: "💔", keywords: "broken heart sad" },
  { char: "💯", keywords: "hundred perfect score keep it" },
  { char: "✅", keywords: "check done yes tick" },
  { char: "❌", keywords: "cross no wrong x" },
  { char: "❓", keywords: "question mark" },
  { char: "❗", keywords: "exclamation important" },
  { char: "👀", keywords: "eyes look watching" },
  { char: "🚀", keywords: "rocket launch ship" },
  { char: "🎯", keywords: "target bullseye direct hit" },
  { char: "💡", keywords: "idea lightbulb" },
  { char: "👑", keywords: "crown king queen" },
  { char: "🏆", keywords: "trophy win award" },
  { char: "🍕", keywords: "pizza food" },
  { char: "☕", keywords: "coffee tea" },
  { char: "🍺", keywords: "beer drink" },
  { char: "🎮", keywords: "game controller gaming" },
  { char: "🐶", keywords: "dog puppy" },
  { char: "🐱", keywords: "cat kitten" },
];

/** Default emoji shown before the user types anything into the search box. */
export const DEFAULT_EMOJIS = ["👍", "👎", "😂", "❤️", "🎉", "🔥", "👀", "🙏", "😍", "😢", "😎", "🚀", "💯", "✅", "🤔", "👏"];
